# Panorama Affine Transform Configuration

# Input Data Folder
# Place source images for stitching
data_folder: "data/raw"

# Resize Settings
# 最大寬度與高度，保持長寬比；設 null 表示不做限制
max_width: 1024
max_height: 768

# Preprocessing Options
# 將圖像轉為灰階並做高斯模糊，可提升特徵偵測穩定性
to_gray: false      # true: 轉灰階；false: 保持彩色
blur: true          # true: 套用 Gaussian Blur；false: 不模糊
blur_kernel_size: [5, 5]  # Gaussian 模糊核大小，必須為奇數

# Feature Detector Configuration
# 傳遞給 create_feature_detector 的參數
detector:
  method: "ORB"     # 'ORB', 'SIFT', 'SURF'
  nfeatures: 1500   # ORB 的最大偵測點數
  scaleFactor: 1.2  # SIFT/SURF 專用：金字塔縮放因子

# Matcher Settings (Brute-Force Matcher)
# 使用 OpenCV 常數：6 = cv2.NORM_HAMMING, 4 = cv2.NORM_L2
matcher:
  norm: 6           # 選擇 NORM_HAMMING (6) 或 NORM_L2 (4)
  cross_check: false # 是否啟用交叉檢查

# Ratio Test for KNN Matching
ratio_test: 0.75    # Lowe's ratio test 閾值

# Affine Estimation
estimation:
  method: "partial"      # 'partial'（平移/旋轉/縮放）或 'full'（含剪切）
  ransac_threshold: 3.0  # RANSAC 重投影誤差閾值 (像素)

# Stitching & Blending
stitch:
  do_simple_blend: true   # true: 使用簡易遮罩融合
  do_multiband_blend: true # true: 多頻段金字塔融合
  blend_levels: 4          # 金字塔層數

# Camera Calibration (Optional)
# 若提供校正檔，可先做圖像去畸變
calibration_file: null     # e.g., "calib/camera_calib.npz"

# Output Settings
output_path: "outputs/results/panorama.jpg"
log_path: "outputs/logs/panorama.log"
